# Generated by Django 3.1.7 on 2021-04-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210408_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
